### ISSUE TITLE
Remove packagekit from installation

### ISSUE THREAD

**Issue by matbme** [Vanilla-OS/gnome-software#39]
We need to remove packagekit to prevent gnome-software from trying to apply updates without VSO.

**Comment by mirkobrombin** [comment]
Adding more context: this means re-packing GNOME Software to exclude packagekit from its dependencies, since it is a [direct one](https://packages.vanillaos.org/package/gnome-software).

**Comment by mirkobrombin** [comment]
Closed by https://github.com/Vanilla-OS/gnome-software/commit/13ac7f5947ec7bd5746c9a84c1612fed7e3a93cb https://github.com/Vanilla-OS/gnome-software/commit/803f17acb0c0343072362880a440ae442593a0e0 https://github.com/Vanilla-OS/gnome-software/commit/4d07ebb35ffd92c907c77f7e625b96eb9ab055b9
